[mypy]
# keep strictness for everything else
warn_unused_ignores = True
exclude = ['env', 'common/', 'micropython/', 'devices/']

[mypy-common.*]
follow_imports = skip

[mypy-apscheduler.*]
ignore_missing_imports = True
[mypy-webrepl.*]
ignore_missing_imports = True
